version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: registry-mysql
    restart: always
    environment:
      MYSQL_DATABASE: "registryDatabase"
      MYSQL_USER: "registry"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - ./ddl:/docker-entrypoint-initdb.d
  mysql-admin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  mysql-db:
